package majorprojectsem7.gui;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JPanel;
import majorprojectsem7.core.Graph;
import majorprojectsem7.core.Processor;

/**
 *
 * @author Rajat Bothra
 */
public class ProcessorDisplay extends javax.swing.JPanel {
    
    private Processor pr;
    
    private LayoutManager layout;

    /**
     * Creates new form ProcessorDisplay
     */
    public ProcessorDisplay(Processor p) {
        initComponents();
        pr = p;
        int start = 200;
        int end = 800;
        double ratio = (end - start) / p.getTasksAllocated().get(p.getTasksAllocated().size() - 1).getEndTime();
        //System.out.println(ratio);
        //layout = new GridLayout(1, p.getTasksAllocated().size(), 0, 10);
        //jPanel1.setLayout(layout);
        int startTime = start;
        for (Graph task : p.getTasksAllocated()) {
            JButton jb = new JButton(task.getName());
            jb.setEnabled(false);
            jb.setToolTipText(task.getName() + " (Execution time :" + task.getExecutionTime() + ")");
            jb.setLocation(startTime, 20);
            //System.out.println("task ->" + task.getName() + " : " + startTime + ", ");
            startTime = startTime + (int) ((task.getEndTime() - task.getStartTime()) * ratio);
            jb.setSize((int) ((task.getEndTime() - task.getStartTime()) * ratio), 40);
            jb.setBackground(new Color(255, new Random().nextInt(255), startTime % 255));
            jPanel1.add(jb);
        }
        jLabel1.setText(p.toString());
        validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Processor name ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(647, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
